export const menuList = [
    {
        id:'projects',
        name:'项目管理',
        children:[
            {
                id:'approval',
                name:'项目立项',
            },
            {
                id:'survey',
                name:'项目调研',
            },
            {
                id:'tender',
                name:'招标管理',
            },
            {
                id:'bid',
                name:'投标管理',
            },
            {
                id:'contract',
                name:'项目合同',
            },
            {
                id:'payment',
                name:'项目付款',
            },
            {
                id:'enclosure',
                name:'项目附件',
            },
            {
                id:'comprehensive',
                name:'项目综合浏览',
            },
            {
                id:'directories',
                name:'公司名录',
            },
            {
                id:'paymentSituation',
                name:'付款情况查询',
            },
            {
                id:'paymentPlan',
                name:'付款计划',
            },
            {
                id:'file',
                name:'项目归档'
            }
        ]
    },
    {
        id:'consumables',
        name:'耗材管理',
    },
    {
        id:'run',
        name:'运行维护',
    },
    {
        id:'system',
        name:'系统管理',
    },

]